In [10]:
import numpy as np
import csv
import matplotlib.pyplot as plt
import scipy
import scipy.stats
import math

In [11]:
TEST_VAR1 = 10
TEST_VAR2 = 11.0
TEST_VAR3 = 'blah'

#by default, csv.writer will write each new object (e.g. char, int, float) into a new cell, unless the group
#of objects is bracketed into a list with square brackets (thus the double brackets)
#with open ('150701 sg results/test writing.csv','w') as test_outputfile:
#    writer = csv.writer(test_outputfile, delimiter = ',')
#    writer.writerows([['test_var 1 is:', '%i' % TEST_VAR1], ['test_var 2 is:', '%f' % TEST_VAR2]])
#    writer.writerows([['test_var 3 is:', '%s' % TEST_VAR3]])

    
    
var1 = -1
var2 = 2
var3 = 10
var4 = -5
var5 = 10
var6 = 10
var7 = 11
var8 = 9

arr1 = [var1, var2, var3, var4]

arr2 = [var5, var6, var7, var8]


arr1 = [-x for x in arr1]
print(arr1)


a = arr1
b = arr2

print(a)
print(b)
a = a + b
print(a)

#zipped1 = zip(absarr, arr2)

#print(zipped1)
absarr = np.absolute(arr1)

arr2 = np.asarray(arr2)
arr1 = absarr[:, np.newaxis]
arr2 = arr2[:, np.newaxis]



combined = np.concatenate((arr1, arr2), axis = 1)
print(combined)

ranks = scipy.stats.rankdata(combined[:, 0])
print(ranks)

ranks = np.asarray(ranks)
ranks = ranks[:, np.newaxis]

combined = np.concatenate((ranks, combined), axis = 1)
print(combined)

combined = np.ndarray.tolist(combined)

combined.sort()
combined = np.asarray(combined)
print(combined)


[1, -2, -10, 5]
[1, -2, -10, 5]
[10, 10, 11, 9]
[1, -2, -10, 5, 10, 10, 11, 9]
[[ 1 10]
 [ 2 10]
 [10 11]
 [ 5  9]]
[ 1.  2.  4.  3.]
[[  1.   1.  10.]
 [  2.   2.  10.]
 [  4.  10.  11.]
 [  3.   5.   9.]]
[[  1.   1.  10.]
 [  2.   2.  10.]
 [  3.   5.   9.]
 [  4.  10.  11.]]
