In [30]:
import numpy as np
import csv
#with open('/Users/markfang/Dropbox/UCSD Grad work/RNA-Yeo Lab/Python scripts/ArizonaTmp.csv', 'rU') as data_file:
data_file = open('/Users/markfang/Dropbox/UCSD Grad work/RNA-Yeo Lab/Python scripts/ArizonaTmp.csv', 'rU')
data_table = np.genfromtxt(data_file, delimiter=",")
print(data_table)
avg = np.average(data_table)
print(avg)
print(np.absolute(data_table - avg))
veca = np.zeros(3)
vecb = np.zeros(7)
vecb = vecb[:,np.newaxis]
print(data_table - veca)
print(data_table - vecb)

print(np.median(data_table))
print(data_table / 2)

[[ 65.2  90.1  94.6]
 [ 63.4  88.3  93.7]
 [ 57.   82.7  88.3]
 [ 46.1  70.8  76.4]
 [ 35.8  58.4  64.2]
 [ 28.4  52.1  57.1]
 [ 25.3  49.7  55.3]]
63.9476190476
[[  1.25238095  26.15238095  30.65238095]
 [  0.54761905  24.35238095  29.75238095]
 [  6.94761905  18.75238095  24.35238095]
 [ 17.84761905   6.85238095  12.45238095]
 [ 28.14761905   5.54761905   0.25238095]
 [ 35.54761905  11.84761905   6.84761905]
 [ 38.64761905  14.24761905   8.64761905]]
[[ 65.2  90.1  94.6]
 [ 63.4  88.3  93.7]
 [ 57.   82.7  88.3]
 [ 46.1  70.8  76.4]
 [ 35.8  58.4  64.2]
 [ 28.4  52.1  57.1]
 [ 25.3  49.7  55.3]]
[[ 65.2  90.1  94.6]
 [ 63.4  88.3  93.7]
 [ 57.   82.7  88.3]
 [ 46.1  70.8  76.4]
 [ 35.8  58.4  64.2]
 [ 28.4  52.1  57.1]
 [ 25.3  49.7  55.3]]
63.4
[[ 32.6   45.05  47.3 ]
 [ 31.7   44.15  46.85]
 [ 28.5   41.35  44.15]
 [ 23.05  35.4   38.2 ]
 [ 17.9   29.2   32.1 ]
 [ 14.2   26.05  28.55]
 [ 12.65  24.85  27.65]]
