In [7]:
import numpy as np
import csv
#with open('/Users/markfang/Dropbox/UCSD Grad work/RNA-Yeo Lab/Python scripts/ArizonaTmp.csv', 'rU') as data_file:
data_file = open('/Users/markfang/Dropbox/UCSD Grad work/RNA-Yeo Lab/ipython test data/ripley.csv', 'rU')
data_table = np.genfromtxt(data_file, delimiter=",")
print(np.shape(data_table))
print(data_table[0,:])
#note that order applies to both how the original ndarray is read, and how the new
#ndarray is written.  to separately denote how the original ndarray is to be read,
#try using the ravel function
print(np.reshape(data_table[0,:], (2,3), order = 'F'))




a = np.arange(6).reshape((3, 2))
print(a)
print(a[:,1])
#practice with the ravel function
print(np.reshape(np.ravel(a, order='F'), (2, 3), order='F'))
print(np.reshape(np.ravel(a, order='C'), (2, 3), order='F'))

(4, 6)
[ 1.0637  1.0678  1.0719  1.0763  1.0807  1.0857]
[[ 1.0637  1.0719  1.0807]
 [ 1.0678  1.0763  1.0857]]
[[0 1]
 [2 3]
 [4 5]]
[1 3 5]
[[0 4 3]
 [2 1 5]]
[[0 2 4]
 [1 3 5]]
