In [7]:
import numpy as np
import csv
import matplotlib.pyplot as plt
import scipy
import scipy.stats
import math

In [9]:
#reorder the datapoints so that each column is a separate plate, and reading down the column
#equals reading across rows on the plate

data_file = open('/Users/markfang/Dropbox/UCSD Grad work/RNA-Yeo Lab/Data - analyses/SG project/screening/granule area to nuclear area analyses of large screens/140807 hek293xt ucsf genentech/before unarranged.csv', 'rU')
data_table = np.genfromtxt(data_file, delimiter=',')

#the actual data is listed in the following rows and columns; the rest are
#data table label strings
FIRSTROW = 4
LASTROW = 64
FIRSTCOL = 1
LASTCOL = 5

data_table = data_table[FIRSTROW:LASTROW, FIRSTCOL:LASTCOL]
print(data_table)

num_rows = data_table.shape[0]
num_cols = data_table.shape[1]

#number of plates, rows, columns
PLATES = 4
PLATE_ROWS = 5
PLATE_COLS = 12

for i in range(num_cols):
    rearranged = np.reshape(data_table[:, i], (PLATE_ROWS, PLATE_COLS), order = 'F' )
    data_table[:, i] = np.reshape(np.ravel(rearranged, order = 'C'), num_rows)
    
print(data_table)

#with open ('/Users/markfang/Dropbox/UCSD Grad work/RNA-Yeo Lab/Data - analyses/SG project/screening/granule area to nuclear area analyses of large screens/140807 hek293xt ucsf genentech/before 2.csv','w') as rearranged_outputfile:
#    writer = csv.writer(rearranged_outputfile, lineterminator = '\n')
#    writer.writerows(data_table)

[[ 0.12517957  0.15896021  0.11647639  0.14446917]
 [ 0.15288903  0.14654335  0.11556824  0.14982193]
 [ 0.14028822  0.16413753  0.13181401  0.15084178]
 [ 0.16574551  0.15541992  0.12330004  0.15020311]
 [ 0.10352427  0.12452314  0.1250768   0.14997809]
 [ 0.1545181   0.16448103  0.11236438  0.13707233]
 [ 0.17917078  0.15068591  0.13138243  0.13997399]
 [ 0.18782201  0.1667361   0.12869258  0.14498271]
 [ 0.16981743  0.13514772  0.1137846   0.13696179]
 [ 0.12356736  0.15201176  0.12380662  0.13572764]
 [ 0.18033811  0.15022398  0.11149865  0.12896366]
 [ 0.17189962  0.1712831   0.13030832  0.14255483]
 [ 0.16279901  0.16232941  0.14441419  0.14533255]
 [ 0.15495219  0.16996756  0.11837331  0.13858637]
 [ 0.12012903  0.15124766  0.13748615  0.13149254]
 [ 0.19405116  0.15854119  0.10053626  0.12697446]
 [ 0.16595619  0.15676757  0.11751373  0.12359318]
 [ 0.17169646  0.16961331  0.11804201  0.13660036]
 [ 0.2160859   0.16210639  0.12176846  0.13105889]
 [ 0.17307519  0.16439309  0.13