In [1]:
import numpy as np
za = np.zeros([3,3])
ast = np.array([1, 2, 3])
za


array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [2]:
#ast
za+=ast
za

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])

In [3]:
za+=ast[:,np.newaxis]
#ast.shape
za


array([[ 2.,  3.,  4.],
       [ 3.,  4.,  5.],
       [ 4.,  5.,  6.]])

In [4]:
"""comment"""

'comment'

In [5]:
#using * operator on ndarray multiplies array element-wise
za = za * 2
za

array([[  4.,   6.,   8.],
       [  6.,   8.,  10.],
       [  8.,  10.,  12.]])

In [6]:
az = range(10)
az

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
#using * operator on array duplicates array
az = az * 2
az

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]